version: '3.8'
services:
  pdv:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./pdv.db:/app/pdv.db      # persist SQLite database
    environment:
      - ENV=development
      - DATABASE_URL=sqlite:///./pdv.db
