<%text>#
# This script is generated by Alembic and serves as a template for future migrations.
#</%text>
from alembic import op
import sqlalchemy as sa

def upgrade():
    pass

def downgrade():
    pass
